# Generated by Django 5.2.7 on 2025-12-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userauthtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserAuthToken',
        ),
    ]
