# Generated by Django 5.2.7 on 2025-12-01 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('parent_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('level', models.IntegerField(default=0)),
                ('total_vehicles', models.IntegerField(default=0)),
                ('online_vehicles', models.IntegerField(default=0)),
                ('no_connection_vehicles', models.IntegerField(default=0)),
                ('long_offline_vehicles', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Группа ТС',
                'verbose_name_plural': 'Группы ТС',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['parent_id'], name='dashboard_g_parent__0503c4_idx'), models.Index(fields=['level'], name='dashboard_g_level_364ddc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('speed', models.FloatField(default=0)),
                ('fuel_level', models.FloatField(blank=True, null=True)),
                ('connection_status', models.CharField(default='offline', max_length=20)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('group_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['connection_status'], name='dashboard_v_connect_0d89db_idx'), models.Index(fields=['group_id'], name='dashboard_v_group_i_43846c_idx'), models.Index(fields=['last_update'], name='dashboard_v_last_up_a6d7e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_status', models.CharField(max_length=20)),
                ('speed', models.FloatField(default=0)),
                ('fuel_level', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.vehicle')),
            ],
            options={
                'verbose_name': 'История ТС',
                'verbose_name_plural': 'История ТС',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['vehicle', 'recorded_at'], name='dashboard_v_vehicle_4ca7c5_idx'), models.Index(fields=['recorded_at'], name='dashboard_v_recorde_7398aa_idx')],
            },
        ),
    ]
