# Generated by Django 5.2.7 on 2025-11-06 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_userauthtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='Внешний ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ТС')),
                ('license_plate', models.CharField(blank=True, max_length=20, verbose_name='Госномер')),
                ('last_location', models.JSONField(blank=True, null=True, verbose_name='Последняя локация')),
                ('current_speed', models.FloatField(blank=True, null=True, verbose_name='Текущая скорость')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
    ]
