# Generated by Django 5.2.7 on 2025-11-09 22:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userauthtoken'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('overspeed', 'Превышение скорости'), ('fuel_theft', 'Кража топлива'), ('geofence', 'Выезд из геозоны'), ('offline', 'Потеря связи'), ('maintenance', 'ТО')], max_length=20, verbose_name='Тип алерта')),
                ('alert_level', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('critical', 'Критично')], max_length=20, verbose_name='Уровень важности')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('alert_data', models.JSONField(blank=True, default=dict, verbose_name='Данные алерта')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время решения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Алерт ТС',
                'verbose_name_plural': 'Алерты ТС',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_level',
            field=models.FloatField(default=0, verbose_name='Уровень топлива'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_moving',
            field=models.BooleanField(default=False, verbose_name='В движении'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_coords_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последних координат'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_data_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последних данных'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='schema_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID схемы'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('truck', 'Грузовик'), ('car', 'Легковой автомобиль'), ('special', 'Спецтехника'), ('bus', 'Автобус')], default='truck', max_length=20, verbose_name='Тип ТС'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_speed',
            field=models.FloatField(default=0, verbose_name='Текущая скорость'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_location',
            field=models.JSONField(blank=True, default=dict, verbose_name='Последнее местоположение'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Госномер'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.organization', verbose_name='Организация'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['external_id'], name='vehicles_ve_externa_2d65d2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization'], name='vehicles_ve_organiz_171de4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_online'], name='vehicles_ve_is_onli_8b2aae_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['last_update'], name='vehicles_ve_last_up_9a5bc6_idx'),
        ),
        migrations.AddField(
            model_name='vehiclealert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем решено'),
        ),
        migrations.AddField(
            model_name='vehiclealert',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='vehiclealert',
            index=models.Index(fields=['vehicle', 'created_at'], name='vehicles_ve_vehicle_443268_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclealert',
            index=models.Index(fields=['is_resolved'], name='vehicles_ve_is_reso_9e121d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclealert',
            index=models.Index(fields=['alert_type'], name='vehicles_ve_alert_t_9a079b_idx'),
        ),
    ]
