# Generated by Django 5.2.7 on 2025-12-01 09:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclealert_vehicle_address_vehicle_fuel_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDataSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speed', models.FloatField(default=0, verbose_name='Скорость')),
                ('fuel_level', models.FloatField(default=0, verbose_name='Уровень топлива')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('engine_hours', models.FloatField(default=0, verbose_name='Моточасы')),
                ('total_distance', models.FloatField(default=0, verbose_name='Общий пробег')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время снимка')),
            ],
            options={
                'verbose_name': 'Снимок данных ТС',
                'verbose_name_plural': 'Снимки данных ТС',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='vehiclealert',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='vehiclealert',
            name='vehicle',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_ve_organiz_171de4_idx',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_moving',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_coords_time',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_data_time',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_location',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
        migrations.AddField(
            model_name='vehicledatasnapshot',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='vehicles.vehicle'),
        ),
        migrations.DeleteModel(
            name='VehicleAlert',
        ),
        migrations.AddIndex(
            model_name='vehicledatasnapshot',
            index=models.Index(fields=['vehicle', 'timestamp'], name='vehicles_ve_vehicle_1036ed_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledatasnapshot',
            index=models.Index(fields=['timestamp'], name='vehicles_ve_timesta_e2f3a3_idx'),
        ),
    ]
